<header>
	<div class="navbar navbar-inverse navbar-fixed-top clearfix"
		 style="
		 		box-shadow: 0px 0px 40px rgba(0, 0, 0, 1);
   		   -moz-box-shadow: 0px 0px 40px rgba(0, 0, 0, 1);
		-webkit-box-shadow: 0px 0px 40px rgba(0, 0, 0, 1);
		 		max-height: 30px;
		 		z-index: 5000;
			   ">
		<div class="navbar-inner" style="max-height: 30px;">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="#/">SupportCenter</a>
				<div class="nav-collapse">
					<div class="btn-group pull-left">
						<button class="btn btn-inverse">Ticketsystem</button>
						<button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu" >
							<!-- dropdown menu links -->
                            <li>
                                <a href="#/get-list">Ticket &Uuml;bersicht</a>
                                <a href="#/login">Login</a>
                            	<a href="#/ticketsystem">Ticketsystem</a>

                            	

                            </li>
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn btn-inverse">Kalender</button>
						<button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn btn-inverse">Terminverwaltung</button>
						<button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
					<div class="btn-group pull-left clearfix">
						<button class="btn btn-inverse">Statistik</button>
						<button class="btn btn-inverse dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>


					<!--
					<br class="clearfix" />
					-->
					
					<div class="btn-group pull-right" style="right: 25px;">
						<div class="dropdown">
							<button class="btn btn-info dropdown-toggle" data-toggle="dropdown" style="min-width: 96px;">
								Suche<span ng-class="{'hide': !keywords}">: {{keywords}}</span> <a href="#searchform"><span class="caret" id="searcharrow"></span></a>
							</button>
							<div class="dropdown-menu well pull-right" style="padding: 15px; padding-bottom: 0px; margin-top: 6px;">
								<form class="form-search" ng-submit="search()">
									<input type="text" ng-model="keywords" class="input-medium search-query" placeholder="search..." style="width: 300px;"/>
									<button type="submit" class="btn" ng-click="showSearch()" id="searchsubmit">Search</button>
								</form>
							</div>
						</div>
					</div>

					<div class="dropdown pull-right" style="right: 25px;">
						<button class="btn btn-danger dropdown-toggle" data-toggle="dropdown" style="width: 96px;">
							Login <a href="#searchform"><span class="caret" id="searcharrow"></span></a>
						</button>
						<div class="dropdown-menu well" style="padding: 15px; padding-bottom: 0px; margin-top: 6px;">
							<form class="form-inline pull-right" style="width: 220px;">
								<input type="text" class="input-small pull-left" placeholder="Email" style="margin-top: 5px;">
								<input type="password" class="input-small pull-right" placeholder="Password" style="margin-top: 5px;">
								<label class="checkbox pull-left" style="margin-top: 5px;">
								<input type="checkbox"> Remember me </label>
								<button type="submit" class="btn pull-right">Sign in</button>
							</form>
						</div>
					</div>

					<div class="dropdown pull-right" style="right: 30px;" ng-controller="ChatWindowCtrl">
						<button class="btn btn-success dropdown-toggle" data-toggle="dropdown" style="width: 96px;">
							Chat <a href="" ng-click="chatWindow()"><span class="caret"></span></a>
						</button>
						<div id="chat" class="dropdown-menu well" style="position: absolute; right: -205px; padding: 15px; padding-bottom: 0px; margin-top: 6px;">
							<div class="pull-right" style="width: 300px; border-left: 1px solid white;">
								<div>
									<div pub-key="pub-a22fbc92-a78f-4420-8c01-0dd18fafdd6d" 
										 sub-key="sub-dc04a400-1322-11e2-bae3-17e29d4769dd" 
										 ssl="off" 
										 origin="pubsub.pubnub.com" 
										 id="pubnub">
									</div>
									<script type="text/javascript" src="http://cdn.pubnub.com/pubnub-3.1.min.js"></script>
									

									<div ng-controller="ChatCtrl">
									    <div class="progress progress-striped active" id="progress_bar">
									    	<div class="bar" style="width: 100%;"></div>
									    </div>
									    <div class="well" style="color: black;">
											<b>Status: {{realtimeStatus}} </b>
									        <form class="form-horizontal">
									            
									            <label>Name:</label>
									            <input placeholder="Your Name" type="text" name="username" ng-model="message.username" style="width: 150px;"/> <br/>
												
												<label>Email:</label> 
												<input placeholder="Your Email" type="text" name="email" ng-model="message.email" style="width: 150px;"/> <br/>             
									            
									            <label>Message:</label> 
									            <textarea placeholder="What's on your mind?" rows="3" name="text" ng-model="message.text" style="width: 150px; height: 60px;"></textarea>
									            
									            <button type="submit" ng-click="publish()" class="btn btn-primary" style="width: 100px; margin-top: 5px;">Send</button>     
									        </form>        									    	

									        <hr/>

											<!-- Message List -->
											<div id="messages" class="table-striped">
											    <div class="message" ng-repeat="message in messages" cool-fade style="border: 0px solid black;">
												    <div class="avatar-frame pull-left" style="width: 20px; border: 1px solid black;">
												    	<img ng-src="http://www.gravatar.com/avatar/{{message.email | gravatarHash}}?s=60"
												    		 class="avatar avatar-60 photo" 
												    		 height="20" width="20"/>
												    </div>
											    	<p class="user pull-left">{{message.username}} said:</p>
											    	<br />
											        <div class="text pull-left" style="width: 250px; word-wrap: break-word;">{{message.text}}</div>
											        <br />
											    </div>
											</div>      
											
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>
	</div>
</header>



<div id="content" ng-view style="overflow: hidden; position: absolute; right: -200px; width: 1345px;">
	<!-- content wird hier rein geladen -->
</div>


