<header>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="#">SupportCenter</a>
				<div class="nav-collapse">
					<div class="btn-group pull-left">
						<button class="btn">Ticketsystem</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
							<a class="btn btn-navbar" href="<?php echo $this->baseUrl() . '/request/ticketoverview/'?>" name="ticketsystem">Ticket &Uuml;bersicht</a>
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn">Kalender</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn">Terminverwaltung</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn">Instant Messaging</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
					<div class="btn-group pull-left">
						<button class="btn">Statistik</button>
						<button class="btn dropdown-toggle" data-toggle="dropdown">
							<span class="caret"></span>
						</button>
						<ul class="dropdown-menu">
							<!-- dropdown menu links -->
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="login">
		<a href="<?php echo $this->baseUrl() . '/auth/login'?>">Login</a>
	</div>
</header>
<script>
$(function() {
	$( "#left" ).resizable();
});
</script>
<!--
<div id="left">
	<nav id="menu">
		<a href="<?php // echo $this->baseUrl() . '/index/#'?>">menu1</a>
		<a href="<?php // echo $this->baseUrl() . '/index/#'?>">menu2</a>
		<a href="<?php // echo $this->baseUrl() . '/index/#'?>">menu3</a>
		<a href="<?php // echo $this->baseUrl() . '/index/#'?>">menu4</a>
		<a href="<?php // echo $this->baseUrl() . '/index/#'?>">menu5</a>
	</nav>
</div>
-->
<div id="content">
	
</div>
<script type="text/javascript">
		$('nav a').click(function( e ){
			var $this = $(this);

			// remove CSS class "active"
			$this.parents('nav').find('a').removeClass('active');

			// add CSS class "active"
			$this.addClass('active');

			// Don't use Browser Default
			e.preventDefault();

			if($('a[name="ticketsystem"]')){
				$('#content').load( $(this).attr('href'));
				ts_get_liste();
			}
			
			// load href-link in DIV ID "content"
			$('#content').load( $(this).attr('href'));
			//, ('#wrapper') 
		});
		$('div a').click(function( e ){
			// Don't use Browser Default
			e.preventDefault();
			
			// Load href-link in DIV ID "login"
			$('#login').load( $(this).attr('href'), ('#loginWrapper'));
		});
		
//});
</script>