


<div class="tabbable tabs-left" style="margin-top: 1px; z-index: 0;">
	<ul class="nav nav-tabs">
		<li class="btn-inverse" style="width: 188px;"><a href="#tab1" data-toggle="tab">Eingang</a></li>
		<li class="btn-inverse" ><a href="#tab2" data-toggle="tab">Section2</a></li>
		<li class="btn-inverse" ><a href="#tab3" data-toggle="tab">Bearbeitung</a></li>
		<li class="btn-inverse" ><a href="#tab4" data-toggle="tab">Ausgang</a></li>
		<li class="btn-inverse" ><a href="#tab5" data-toggle="tab">Bla</a></li>
	</ul>
	<div class="tab-content">
		<div class="tab-pane" id="tab1">
			<p>ich bin Sektion 1</p>
		</div>
		<div class="tab-pane" id="tab2">
			<p>ich bin Sektion 2</p>
		</div>
		<div class="tab-pane" id="tab3">
			
			<?php require_once "/localhost" . $this->baseUrl() . "/ticketsystem/eingang"; ?>

		</div>
		<div class="tab-pane" id="tab4">
			<p>bla</p>
		</div>
		<div class="tab-pane" id="tab5">
			<p>bla</p>
		</div>
	</div>
</div>
