<div class="well well-small" style="width:97.5%; color:#222; max-height: 400px; min-height: 399px;" ng-controller="GetListCtrl">
	<div class="accordion" id="accordion2" ng-repeat="result in results" style="margin: 0; height: 40px;">
	  

	  <div class="accordion-group">
	    <div class="accordion-heading">
	      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse{{result.IdTicketsystem}}" ng-click="showMessage($index)">
	       	<script type="text/javascript">
	  			console.log();
	  		</script>
	       	
	       	<strong>{{result.Fehlermeldung}}</strong>

	       	<span class="pull-right">{{result.Datum}}</span>
	      </a>
	    </div>
	    <!--
	    <div id="collapse{{result.IdTicketsystem}}" class="accordion-body collapse">
	      <div class="accordion-inner">
			<blockquote>
				<p>{{result.Fehlertext}}</p>
				<small>{{result.Datum}}</small>
			</blockquote>
	      </div>
	    </div>
	-->
	  </div>
	</div>

	<div>
		<ul class="pager">
		  <li class="previous"  ng-show="page > 1">
		    <a href="" ng-click="getNewer()">&larr; Newer</a>
		  </li>
		  <div >
		  	
		  </div>
		  <li class="next">
		    <a href="" ng-click="getOlder()">Older &rarr;</a>
		  </li>
		</ul>
	</div>

	<br class="clearfix " />

	<div class="well well-small" style="margin-left: -10px; margin-top: -32px; width: 100%; max-height: 400px;" ng-show="currentMsg">
		<div class="well well-small" style="height: 20px; max-height: 20px;">
			<p class="pull-left"><span>Betreff: </span>{{currentMsg.Debitor}} // {{currentMsg.Produkt}} // {{currentMsg.Fehlermeldung}}</p>
			<p class="pull-right"><span>Ticket-ID: </span>{{currentMsg.IdTicketsystem}}</p>
		</div>
		<div class="well well-small" style="height: 280px; max-height: 280px">
			<blockquote>
				<p>{{currentMsg.Fehlertext}}</p>
				<small>{{currentMsg.Datum}}</small>


				<script type="text/javascript">
					console.log('bla');

				</script>	
			</blockquote>
		</div>
	</div>

</div>