<div class="well" style="width:96%; color:#222;" ng-controller="GetListCtrl">
	<div class="accordion" id="accordion2" ng-repeat="result in results">
	  <div class="accordion-group">
	    <div class="accordion-heading">
	      <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapse{{result.IdTicketsystem}}">
	       	<strong>{{result.Fehlermeldung}}</strong>
	       	<span class="pull-right">{{result.Von}}</span>
	      </a>
	    </div>
	    <div id="collapse{{result.IdTicketsystem}}" class="accordion-body collapse">
	      <div class="accordion-inner">
			<blockquote>
				<p>{{result.Fehlertext}}</p>
				<small>{{result.Datum}}</small>
			</blockquote>
	      </div>
	    </div>
	  </div>
	</div>

	<div>
	
	<ul class="pager">
	  <li class="previous"  ng-show="page > 1">
	    <a href="" ng-click="getNewer()">&larr; Newer</a>
	  </li>
	  <li class="next">
	    <a href="" ng-click="getOlder()">Older &rarr;</a>
	  </li>
	</ul>
	
	<!--	<ul class="pager">
			<li class="previous">
				<div ng-show="page > 1">
					<button class="btn btn-primary" ng-click="getNewer()">&larr; Newer</button>
				</div>
			</li>
			<li class="next">
				<div ng-hide="showLoading">
					<button class="btn btn-primary" ng-click="getOlder()">Older &rarr;</button>
				</div>
			</li>
		</ul>-->
	</div>

	<br class="clearfix " />
</div>