<?php
// This file generated by Propel 1.6.7 convert-conf target
return array (
  'BaseTicketVerlauf' => 'SmgSupportCenter/om/BaseTicketVerlauf.php',
  'BaseTicketVerlaufPeer' => 'SmgSupportCenter/om/BaseTicketVerlaufPeer.php',
  'BaseTicketVerlaufQuery' => 'SmgSupportCenter/om/BaseTicketVerlaufQuery.php',
  'BaseTicketsystem' => 'SmgSupportCenter/om/BaseTicketsystem.php',
  'BaseTicketsystemPeer' => 'SmgSupportCenter/om/BaseTicketsystemPeer.php',
  'BaseTicketsystemQuery' => 'SmgSupportCenter/om/BaseTicketsystemQuery.php',
  'TicketVerlauf' => 'SmgSupportCenter/TicketVerlauf.php',
  'TicketVerlaufPeer' => 'SmgSupportCenter/TicketVerlaufPeer.php',
  'TicketVerlaufQuery' => 'SmgSupportCenter/TicketVerlaufQuery.php',
  'TicketVerlaufTableMap' => 'SmgSupportCenter/map/TicketVerlaufTableMap.php',
  'Ticketsystem' => 'SmgSupportCenter/Ticketsystem.php',
  'TicketsystemPeer' => 'SmgSupportCenter/TicketsystemPeer.php',
  'TicketsystemQuery' => 'SmgSupportCenter/TicketsystemQuery.php',
  'TicketsystemTableMap' => 'SmgSupportCenter/map/TicketsystemTableMap.php',
);