<?php
// This file generated by Propel 1.6.7 convert-conf target
// from XML runtime conf file /opt/lampp/htdocs/SmgSupportCenter/build/runtime-conf.xml
$conf = array (
  'datasources' => 
  array (
    'SmgSupportCenter' => 
    array (
      'adapter' => 'mysql',
      'connection' => 
      array (
        'dsn' => 'mysql:host=roundel.de;dbname=d01324f7',
        'user' => 'd01324f7',
        'password' => 'VkPof7bhLeg3uLUJ',
      ),
    ),
    'default' => 'SmgSupportCenter',
  ),
  'generator_version' => '1.6.7',
);
$conf['classmap'] = include(dirname(__FILE__) . DIRECTORY_SEPARATOR . 'classmap-SmgSupportCenter-conf.php');
return $conf;